n_agents: 2
obs_dim: 213
action_dim: 2
batch_size: 1024
capacity: 1000000
n_explore: 100
n_episodes: 20000
reward_decay: 0.95
tau: 0.01
lr: 0.0001
cuda: True
max_steps: 1000
reward_scale: 0.01
soft_update_interval: 100
seed: 10001
