# env settings
scenario_name: simple_tag
max_episode_length: 100
time_steps: 2000000
num_advs: 1

# training hyperparameters
lr_actor: 0.0001
lr_critic: 0.001
# exploration factor
epsilon: 0.1
noise_rate: 0.1
# reward decay
gamma: 0.95
# soft update rate
tau: 0.01
cuda: False
# experience
batch_size: 256
buffer_size: 500000

# settings about saving models and logs
log_dir: .\MultiAgentDeepDeterministicPolicyGradient\logs
save_dir: .\MultiAgentDeepDeterministicPolicyGradient\models

# evaluation settings
eval_interval: 10000
eval_episodes: 10
eval_episodes_len: 100
