hidden_size: 256
lr_a: 4.0e-4
lr_c: 4.0e-4
reward_decay: 0.99
buffer_size: 100000
batch_size: 8192
env: Pendulum-v1
max_epoch: 200000
log_dir: TwinDelayedDeepDeterministicPolicyGradient(TD3)\logs
tau: 0.01
action_noise: 0.1
policy_noise: 0.2
noise_clip: 0.5
update_policy_interval: 2
cuda: True
display_interval: 100
model_save_dir: TwinDelayedDeepDeterministicPolicyGradient(TD3)\saved_models
save_frequency: 2000
actor_dir:
critic_dir:
