hidden_size: 256
lr_a: 3.0e-4
lr_c: 3.0e-4
reward_decay: 0.99
buffer_size: 100000
batch_size: 1024
env: LunarLanderContinuous-v2
max_epoch: 20000
log_dir: TwinDelayedDeepDeterministicPolicyGradient(TD3)\logs
tau: 0.02
policy_noise: 0.3
noise_clip: 0.3
update_policy_interval: 5
cuda: True
display_interval: 100
model_save_dir: TwinDelayedDeepDeterministicPolicyGradient(TD3)\saved_models
save_frequency: 500
actor_dir: ~
critic_dir: ~
