hidden_size: 256
lr_a: 1.0e-4
lr_c: 1.0e-4
reward_decay: 0.99
buffer_size: 114514
batch_size: 256
env: LunarLanderContinuous-v2
max_epoch: 50000
log_dir: TwinDelayedDeepDeterministicPolicyGradient(TD3)\logs
tau: 0.01
policy_noise: 0.1
noise_clip: 0.1
update_policy_interval: 5
cuda: True
display_interval: 100
model_save_dir: TwinDelayedDeepDeterministicPolicyGradient(TD3)\saved_models
save_frequency: 500
actor_dir: TwinDelayedDeepDeterministicPolicyGradient(TD3)\saved_models\ACTOR 2022-01-15 04-13-48.pth
critic_dir:
################
# PER SETTINGS #
################

#use HER?
HER: True
mem_alpha: 0.6
mem_beta: 0.4
beta_increment: 0.00001
epsilon: 1.0e-5
clipped_abs_error: 1.0
