hidden_size: 256
lr_a: 1.0e-3
lr_c: 1.0e-3
reward_decay: 0.99
buffer_size: 114514
batch_size: 512
env: Pendulum-v1
max_epoch: 50000
log_dir: TwinDelayedDeepDeterministicPolicyGradient(TD3)\logs
tau: 0.05
policy_noise: 0.2
noise_clip: 0.5
update_policy_interval: 2
cuda: True
display_interval: 100
model_save_dir: TwinDelayedDeepDeterministicPolicyGradient(TD3)\saved_models
save_frequency: 2000
actor_dir: TwinDelayedDeepDeterministicPolicyGradient(TD3)\saved_models\ACTOR 2022-01-15 04-13-48.pth
critic_dir:
################
# PER SETTINGS #
################

#use HER?
HER: True
mem_alpha: 0.6
mem_beta: 0.4
beta_increment: 0.001
epsilon: 1.0e-5
clipped_abs_error: 10.0
