env: LunarLanderContinuous-v2
cuda: True
# network training settings
episodes: 5000
repeat_times: 50
lr_a: 4.0e-4
lr_c: 4.0e-4
hidden_size: 256
reward_decay: 0.985
tau: 0.005
act_noise: 0.1
target_noise: 0.2
tar_noise_clip: 0.5
# "delayed" means update the actor after updating critics
policy_delay: 2
# memory
batch_size: 256
mem_size: 1.0e+6
# tensorboard
log_dir: TwinDelayedDeepDeterministicPolicyGradient(TD3)\logs
# 多少轮展示一下训练进度
display_interval: 10
# 继续训练时ac的目录
actor_dir:
critic_dir:
model_save_dir: TwinDelayedDeepDeterministicPolicyGradient(TD3)\saved_models
save_frequency: 100
